version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 3031:3031

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80


